print ("Question : What is the largest planet in the solar system")
print ("A) Earth")
print ("B) Mars")
print ("C) Jupiter")
print ("D) Saturn")
print ("Correct Answer : C) Jupiter")

house = "🧱"
space = "  "
print (house,house,house,house,house,house)
print (house,space,space,space,space,house)
print (house,space,space,space,space,house)
print (house,space,space,space,space,house)
print (house,space,space,space,space,house)
print (house,space,space,space,space,house)
print (house,house,house,house,house,house)

print ("Presentation: Exploring Huron-Wendat Heritage")
print ("Aspects of Huron-Wendat Cultures:")
print ("- Traditional Practices")
print ("- Art and Craftsmanship")
print ("- Language and Storytelling")
print ("- Community Traditions")
print ("Date: Wednesday, November 15, 2023")
print ("Duration: 60 minutes")